---
name: Example 3
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build Docker1
    runs-on: self-hosted runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker2
      run: |
        docker build -t test .
  build-2:
    name: Build Docker3
    runs-on: self-hosted runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
  build-3:
    name: Build Docker4
    runs-on: self-hosted runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
  build-4:
    name: Build Docker5
    runs-on: self-hosted runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
  build-5:
    name: Build Docker
    runs-on: self-hosted runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
