---
name: Example 1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_review_comment:
    branches:
     -main
     -swathida-byte-patch/**
     -anudeep-pv-patch/**
    types: [recheck]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Hello
      run: |
        echo "Hello World from self hosted runner!!!"
        
        
