name: dependentjobs
on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization
  Tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization
  Run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization
  
