
name: workflow1

on:
  push:
    branches:
      - main

jobs:
  call-worflow:
    runs-on: self-hosted

    steps:
     -  name: Checkout
        uses: actions/checkout@v2
     -  name: wor
        uses: Kitchen/.github/workflow-templates/dummy-ci.yml@main
      

  

  


    

