name: Reusable workflow example

on:
  workflow_run:
    branches: [ main ]
    

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: [ self-hosted ]
    steps:
      - uses: Kitchen/.github/workflows-templates/dummy-ci.yml@v2
      - run: 'echo Found it!'
