
name: Call a reusable workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  call-worflow:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Workflow
      uses: actions/re.yml@v5
      

  

  


    

