
name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-worflow:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: workflowfile
      uses: Kitchen/.github/workflow-templates/dummy-ci.yml@a0b3caed2e077d4f07794fcae2bef611c99e4d5c
      

  

  


    

