name: issuecomment
on:
  pull_request_review:
    types: [submitted,edited, dismissed]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: self-hosted
    steps:
      - run: echo "This PR was approved"
