name: Checkout PR on comment

on:
  pull_request_review_comment:
  pull_request:

jobs:
  pr-commented:
    name: PR commented
    if: contains(github.event.comment.html_url, '/pull/') ||  ${{ github.event.label.name == 'queued' }} 
    runs-on: self-hosted
    steps:
      - run: "echo Found it!"
  pr-commented-1:
    name: PR commented-1
    if: contains(github.event.comment.html_url, '/pull/') 
    runs-on: self-hosted
    steps:
      - run: "echo Found it"
