name: Checkout PR on comment

on:
  pull_request_review_comment:
  pull_request:


jobs:
  pr-commented:
    name: PR commented
    if: ${{ github.event.label.name == 'queued' }} || contains(github.event.comment.body, 're')
    runs-on: self-hosted
    steps: 
     - run: 'echo Found it!'
